project:
  type: website
  output-dir: docs

website:
  title: "Karen Myna Cantor - YA Author"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: books.qmd
        text: Books
      - href: media_kit.qmd
        text: Media Kit
      - href: blog.qmd
        text: Blog
    
    right:
      - text: "Bluesky"
        href: https://bsky.app/profile/karenmcantor.bsky.social
        rel: me
      - text: "Instagram"  
        href: https://www.instagram.com/karenmcantor/
        rel: me
      - text: "Tumblr"  
        href: https://www.tumblr.com/myna-coltress/
        rel: me

format:
  html:
    theme: cerulean
    css: styles.css
    toc: false

editor: visual